name: i_card
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: play_write
      fonts:
        - asset: fonts/play_write_regular.ttf
    - family: roboto
      fonts:
        - asset: fonts/roboto_regular.ttf
